// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:366


#include "DataATypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "DataATypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TestA::DataATypeSupport.

TestA::DataATypeSupport_ptr
TAO::Objref_Traits<TestA::DataATypeSupport>::duplicate (
    TestA::DataATypeSupport_ptr p)
{
  return TestA::DataATypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<TestA::DataATypeSupport>::release (
    TestA::DataATypeSupport_ptr p)
{
  ::CORBA::release (p);
}

TestA::DataATypeSupport_ptr
TAO::Objref_Traits<TestA::DataATypeSupport>::nil (void)
{
  return TestA::DataATypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TestA::DataATypeSupport>::marshal (
    const TestA::DataATypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TestA::DataATypeSupport::DataATypeSupport (void)
{}

TestA::DataATypeSupport::~DataATypeSupport (void)
{
}

TestA::DataATypeSupport_ptr
TestA::DataATypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataATypeSupport::_duplicate (
      dynamic_cast<DataATypeSupport_ptr> (_tao_objref));
}

TestA::DataATypeSupport_ptr
TestA::DataATypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataATypeSupport::_duplicate (
      dynamic_cast<DataATypeSupport_ptr> (_tao_objref));
}

TestA::DataATypeSupport_ptr
TestA::DataATypeSupport::_nil (void)
{
  return 0;
}

TestA::DataATypeSupport_ptr
TestA::DataATypeSupport::_duplicate (DataATypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TestA::DataATypeSupport::_tao_release (DataATypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TestA::DataATypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:TestA/DataATypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TestA::DataATypeSupport::_interface_repository_id (void) const
{
  return "IDL:TestA/DataATypeSupport:1.0";
}

::CORBA::Boolean
TestA::DataATypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TestA::DataADataWriter.

TestA::DataADataWriter_ptr
TAO::Objref_Traits<TestA::DataADataWriter>::duplicate (
    TestA::DataADataWriter_ptr p)
{
  return TestA::DataADataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<TestA::DataADataWriter>::release (
    TestA::DataADataWriter_ptr p)
{
  ::CORBA::release (p);
}

TestA::DataADataWriter_ptr
TAO::Objref_Traits<TestA::DataADataWriter>::nil (void)
{
  return TestA::DataADataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TestA::DataADataWriter>::marshal (
    const TestA::DataADataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TestA::DataADataWriter::DataADataWriter (void)
{}

TestA::DataADataWriter::~DataADataWriter (void)
{
}

TestA::DataADataWriter_ptr
TestA::DataADataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataADataWriter::_duplicate (
      dynamic_cast<DataADataWriter_ptr> (_tao_objref));
}

TestA::DataADataWriter_ptr
TestA::DataADataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataADataWriter::_duplicate (
      dynamic_cast<DataADataWriter_ptr> (_tao_objref));
}

TestA::DataADataWriter_ptr
TestA::DataADataWriter::_nil (void)
{
  return 0;
}

TestA::DataADataWriter_ptr
TestA::DataADataWriter::_duplicate (DataADataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TestA::DataADataWriter::_tao_release (DataADataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TestA::DataADataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:TestA/DataADataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TestA::DataADataWriter::_interface_repository_id (void) const
{
  return "IDL:TestA/DataADataWriter:1.0";
}

::CORBA::Boolean
TestA::DataADataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TestA::DataADataReader.

TestA::DataADataReader_ptr
TAO::Objref_Traits<TestA::DataADataReader>::duplicate (
    TestA::DataADataReader_ptr p)
{
  return TestA::DataADataReader::_duplicate (p);
}

void
TAO::Objref_Traits<TestA::DataADataReader>::release (
    TestA::DataADataReader_ptr p)
{
  ::CORBA::release (p);
}

TestA::DataADataReader_ptr
TAO::Objref_Traits<TestA::DataADataReader>::nil (void)
{
  return TestA::DataADataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TestA::DataADataReader>::marshal (
    const TestA::DataADataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TestA::DataADataReader::DataADataReader (void)
{}

TestA::DataADataReader::~DataADataReader (void)
{
}

TestA::DataADataReader_ptr
TestA::DataADataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataADataReader::_duplicate (
      dynamic_cast<DataADataReader_ptr> (_tao_objref));
}

TestA::DataADataReader_ptr
TestA::DataADataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataADataReader::_duplicate (
      dynamic_cast<DataADataReader_ptr> (_tao_objref));
}

TestA::DataADataReader_ptr
TestA::DataADataReader::_nil (void)
{
  return 0;
}

TestA::DataADataReader_ptr
TestA::DataADataReader::_duplicate (DataADataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TestA::DataADataReader::_tao_release (DataADataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TestA::DataADataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:TestA/DataADataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TestA::DataADataReader::_interface_repository_id (void) const
{
  return "IDL:TestA/DataADataReader:1.0";
}

::CORBA::Boolean
TestA::DataADataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TestA::DataBTypeSupport.

TestA::DataBTypeSupport_ptr
TAO::Objref_Traits<TestA::DataBTypeSupport>::duplicate (
    TestA::DataBTypeSupport_ptr p)
{
  return TestA::DataBTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<TestA::DataBTypeSupport>::release (
    TestA::DataBTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

TestA::DataBTypeSupport_ptr
TAO::Objref_Traits<TestA::DataBTypeSupport>::nil (void)
{
  return TestA::DataBTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TestA::DataBTypeSupport>::marshal (
    const TestA::DataBTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TestA::DataBTypeSupport::DataBTypeSupport (void)
{}

TestA::DataBTypeSupport::~DataBTypeSupport (void)
{
}

TestA::DataBTypeSupport_ptr
TestA::DataBTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataBTypeSupport::_duplicate (
      dynamic_cast<DataBTypeSupport_ptr> (_tao_objref));
}

TestA::DataBTypeSupport_ptr
TestA::DataBTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataBTypeSupport::_duplicate (
      dynamic_cast<DataBTypeSupport_ptr> (_tao_objref));
}

TestA::DataBTypeSupport_ptr
TestA::DataBTypeSupport::_nil (void)
{
  return 0;
}

TestA::DataBTypeSupport_ptr
TestA::DataBTypeSupport::_duplicate (DataBTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TestA::DataBTypeSupport::_tao_release (DataBTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TestA::DataBTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:TestA/DataBTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TestA::DataBTypeSupport::_interface_repository_id (void) const
{
  return "IDL:TestA/DataBTypeSupport:1.0";
}

::CORBA::Boolean
TestA::DataBTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TestA::DataBDataWriter.

TestA::DataBDataWriter_ptr
TAO::Objref_Traits<TestA::DataBDataWriter>::duplicate (
    TestA::DataBDataWriter_ptr p)
{
  return TestA::DataBDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<TestA::DataBDataWriter>::release (
    TestA::DataBDataWriter_ptr p)
{
  ::CORBA::release (p);
}

TestA::DataBDataWriter_ptr
TAO::Objref_Traits<TestA::DataBDataWriter>::nil (void)
{
  return TestA::DataBDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TestA::DataBDataWriter>::marshal (
    const TestA::DataBDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TestA::DataBDataWriter::DataBDataWriter (void)
{}

TestA::DataBDataWriter::~DataBDataWriter (void)
{
}

TestA::DataBDataWriter_ptr
TestA::DataBDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataBDataWriter::_duplicate (
      dynamic_cast<DataBDataWriter_ptr> (_tao_objref));
}

TestA::DataBDataWriter_ptr
TestA::DataBDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataBDataWriter::_duplicate (
      dynamic_cast<DataBDataWriter_ptr> (_tao_objref));
}

TestA::DataBDataWriter_ptr
TestA::DataBDataWriter::_nil (void)
{
  return 0;
}

TestA::DataBDataWriter_ptr
TestA::DataBDataWriter::_duplicate (DataBDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TestA::DataBDataWriter::_tao_release (DataBDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TestA::DataBDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:TestA/DataBDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TestA::DataBDataWriter::_interface_repository_id (void) const
{
  return "IDL:TestA/DataBDataWriter:1.0";
}

::CORBA::Boolean
TestA::DataBDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TestA::DataBDataReader.

TestA::DataBDataReader_ptr
TAO::Objref_Traits<TestA::DataBDataReader>::duplicate (
    TestA::DataBDataReader_ptr p)
{
  return TestA::DataBDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<TestA::DataBDataReader>::release (
    TestA::DataBDataReader_ptr p)
{
  ::CORBA::release (p);
}

TestA::DataBDataReader_ptr
TAO::Objref_Traits<TestA::DataBDataReader>::nil (void)
{
  return TestA::DataBDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TestA::DataBDataReader>::marshal (
    const TestA::DataBDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TestA::DataBDataReader::DataBDataReader (void)
{}

TestA::DataBDataReader::~DataBDataReader (void)
{
}

TestA::DataBDataReader_ptr
TestA::DataBDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataBDataReader::_duplicate (
      dynamic_cast<DataBDataReader_ptr> (_tao_objref));
}

TestA::DataBDataReader_ptr
TestA::DataBDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataBDataReader::_duplicate (
      dynamic_cast<DataBDataReader_ptr> (_tao_objref));
}

TestA::DataBDataReader_ptr
TestA::DataBDataReader::_nil (void)
{
  return 0;
}

TestA::DataBDataReader_ptr
TestA::DataBDataReader::_duplicate (DataBDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TestA::DataBDataReader::_tao_release (DataBDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TestA::DataBDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:TestA/DataBDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TestA::DataBDataReader::_interface_repository_id (void) const
{
  return "IDL:TestA/DataBDataReader:1.0";
}

::CORBA::Boolean
TestA::DataBDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

