// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:366


#include "DataATypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "DataATypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TestA::DataATypeSupport.

TestA::DataATypeSupport_ptr
TAO::Objref_Traits<TestA::DataATypeSupport>::duplicate (
    TestA::DataATypeSupport_ptr p)
{
  return TestA::DataATypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<TestA::DataATypeSupport>::release (
    TestA::DataATypeSupport_ptr p)
{
  ::CORBA::release (p);
}

TestA::DataATypeSupport_ptr
TAO::Objref_Traits<TestA::DataATypeSupport>::nil (void)
{
  return TestA::DataATypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TestA::DataATypeSupport>::marshal (
    const TestA::DataATypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TestA::DataATypeSupport::DataATypeSupport (void)
{}

TestA::DataATypeSupport::~DataATypeSupport (void)
{
}

TestA::DataATypeSupport_ptr
TestA::DataATypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataATypeSupport::_duplicate (
      dynamic_cast<DataATypeSupport_ptr> (_tao_objref));
}

TestA::DataATypeSupport_ptr
TestA::DataATypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataATypeSupport::_duplicate (
      dynamic_cast<DataATypeSupport_ptr> (_tao_objref));
}

TestA::DataATypeSupport_ptr
TestA::DataATypeSupport::_nil (void)
{
  return 0;
}

TestA::DataATypeSupport_ptr
TestA::DataATypeSupport::_duplicate (DataATypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TestA::DataATypeSupport::_tao_release (DataATypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TestA::DataATypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:TestA/DataATypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TestA::DataATypeSupport::_interface_repository_id (void) const
{
  return "IDL:TestA/DataATypeSupport:1.0";
}

::CORBA::Boolean
TestA::DataATypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TestA::DataADataWriter.

TestA::DataADataWriter_ptr
TAO::Objref_Traits<TestA::DataADataWriter>::duplicate (
    TestA::DataADataWriter_ptr p)
{
  return TestA::DataADataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<TestA::DataADataWriter>::release (
    TestA::DataADataWriter_ptr p)
{
  ::CORBA::release (p);
}

TestA::DataADataWriter_ptr
TAO::Objref_Traits<TestA::DataADataWriter>::nil (void)
{
  return TestA::DataADataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TestA::DataADataWriter>::marshal (
    const TestA::DataADataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TestA::DataADataWriter::DataADataWriter (void)
{}

TestA::DataADataWriter::~DataADataWriter (void)
{
}

TestA::DataADataWriter_ptr
TestA::DataADataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataADataWriter::_duplicate (
      dynamic_cast<DataADataWriter_ptr> (_tao_objref));
}

TestA::DataADataWriter_ptr
TestA::DataADataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataADataWriter::_duplicate (
      dynamic_cast<DataADataWriter_ptr> (_tao_objref));
}

TestA::DataADataWriter_ptr
TestA::DataADataWriter::_nil (void)
{
  return 0;
}

TestA::DataADataWriter_ptr
TestA::DataADataWriter::_duplicate (DataADataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TestA::DataADataWriter::_tao_release (DataADataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TestA::DataADataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:TestA/DataADataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TestA::DataADataWriter::_interface_repository_id (void) const
{
  return "IDL:TestA/DataADataWriter:1.0";
}

::CORBA::Boolean
TestA::DataADataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for TestA::DataADataReader.

TestA::DataADataReader_ptr
TAO::Objref_Traits<TestA::DataADataReader>::duplicate (
    TestA::DataADataReader_ptr p)
{
  return TestA::DataADataReader::_duplicate (p);
}

void
TAO::Objref_Traits<TestA::DataADataReader>::release (
    TestA::DataADataReader_ptr p)
{
  ::CORBA::release (p);
}

TestA::DataADataReader_ptr
TAO::Objref_Traits<TestA::DataADataReader>::nil (void)
{
  return TestA::DataADataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TestA::DataADataReader>::marshal (
    const TestA::DataADataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



TestA::DataADataReader::DataADataReader (void)
{}

TestA::DataADataReader::~DataADataReader (void)
{
}

TestA::DataADataReader_ptr
TestA::DataADataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataADataReader::_duplicate (
      dynamic_cast<DataADataReader_ptr> (_tao_objref));
}

TestA::DataADataReader_ptr
TestA::DataADataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataADataReader::_duplicate (
      dynamic_cast<DataADataReader_ptr> (_tao_objref));
}

TestA::DataADataReader_ptr
TestA::DataADataReader::_nil (void)
{
  return 0;
}

TestA::DataADataReader_ptr
TestA::DataADataReader::_duplicate (DataADataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TestA::DataADataReader::_tao_release (DataADataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TestA::DataADataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:TestA/DataADataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* TestA::DataADataReader::_interface_repository_id (void) const
{
  return "IDL:TestA/DataADataReader:1.0";
}

::CORBA::Boolean
TestA::DataADataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

