// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:149

#ifndef _TAO_IDL_DATAAC_PD54HJ_H_
#define _TAO_IDL_DATAAC_PD54HJ_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

// TAO_IDL - Generated from
// d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:35

namespace TestA
{

  // TAO_IDL - Generated from
  // d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:258

  struct DataA;

  typedef
    ::TAO_Var_Var_T<
        DataA
      >
    DataA_var;

  typedef
    ::TAO_Out_T<
        DataA
      >
    DataA_out;

  // TAO_IDL - Generated from
  // d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\structure_ch.cpp:48

  struct  DataA
  {

    // TAO_IDL - Generated from
    // d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    
    typedef DataA_var _var_type;
    typedef DataA_out _out_type;
    
    ::CORBA::Long pos;
    ::TAO::String_Manager name;
    ::CORBA::Long length;
  };

// TAO_IDL - Generated from
// d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:64

} // module TestA

// TAO_IDL - Generated from
// d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:945

  template<>
  class Arg_Traits< ::TestA::DataA>
    : public
        Var_Size_Arg_Traits_T<
            ::TestA::DataA,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_ch.cpp:43


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TestA::DataA &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, TestA::DataA &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\softwaredevelopment\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1686
#if defined (__ACE_INLINE__)
#include "DataAC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

